### ISSUE TITLE
Cannot add ubuntuce Repo Key

### ISSUE THREAD

**Issue by chadwickBushnell** [jeremehancock/docs.ubuntuce.com-content#1]
I attempt to add ubuntuce repository key using the following command:
`wget https://job.ubuntuce.com/KEY.gpg && gpg --output ubuntuce.gpg --dearmor KEY.gpg && sudo mv ubuntuce.gpg /usr/share/keyrings/ && rm KEY.gpg`
I get the following output:
```
Resolving job.ubuntuce.com (job.ubuntuce.com)... 162.210.96.116
Connecting to job.ubuntuce.com (job.ubuntuce.com)|162.210.96.116|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 0
Saving to: ‘KEY.gpg’

KEY.gpg                      [ <=>                              ]       0  --.-KB/s    in 0s      

2022-11-03 05:12:12 (0.00 B/s) - ‘KEY.gpg’ saved [0/0]

gpg: no valid OpenPGP data found.
```

**Comment by jeremehancock** [comment]
Thank you very much for reporting this issue. I have fixed the issue. Somehow the KEY.gpg file got erased. I have corrected that and tested a fresh install of the UbuntuCE Repo. I will look into adding some tests/monitoring to avoid this issue in the future.

Please let me know if you have any further issues. I will close this issue, but if you still have any issues please do open another.

Thank you!!

**Comment by chadwickBushnell** [comment]
That worked perfectly. Thank you.
